name: Rebuild SEMPA embeddings

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir beautifulsoup4 httpx

      - name: Ingest SEMPA
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          python scripts/ingest_sempa.py \
            --urls-file scripts/urls.txt \
            --out clients/sempa/embeddings_v2

      - name: Commit embeddings (skip CI)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: refresh SEMPA embeddings_v2 [skip ci]"
          file_pattern: clients/sempa/embeddings_v2/*
