name: Rebuild SEMPA embeddings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"   # Mondays 06:00 UTC

concurrency:
  group: ingest-weekly
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt beautifulsoup4 httpx

      - name: Build embeddings (unbuffered) with keepalive
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
          PYTHONUNBUFFERED: "1"
        run: |
          set -e
          python -u scripts/ingest_sempa.py --urls-file scripts/urls.txt --out clients/sempa/embeddings_v2 & pid=$!
          while kill -0 $pid 2>/dev/null; do
            echo "::notice:: ingest running (pid=$pid) ..."
            sleep 20
          done
          wait $pid
          ls -la clients/sempa/embeddings_v2

      - name: Commit artifacts (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add clients/sempa/embeddings_v2/*
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update embeddings_v2 [skip ci]"
            git push origin ${{ github.ref }}
          fi
