name: Ingest (test only, no commit)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Separate group so this job never cancels the full ingest.
    concurrency:
      group: sempa-ingest-test-${{ github.run_id }}
      cancel-in-progress: false

    env:
      EMBED_MODEL: text-embedding-3-small
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 httpx

      - name: Show URL preview (first 10)
        run: |
          test -f scripts/urls.txt || (echo "Missing scripts/urls.txt" && exit 1)
          echo "Preview:"; head -n 10 scripts/urls.txt

      - name: Dry-run ingest to /tmp (with heartbeat)
        shell: bash
        run: |
          set -e
          ( while true; do echo "::notice::heartbeat $(date -u +"%H:%M:%S")"; sleep 20; done ) &
          HB=$!
          python scripts/ingest_sempa.py --urls-file scripts/urls.txt --out /tmp/embeddings_check
          kill $HB || true
          ls -la /tmp/embeddings_check
