name: Test SEMPA ingest (no commit)

on:
  workflow_dispatch:

permissions:
  contents: read

# Unique group per run so nothing gets auto-canceled
concurrency:
  group: ingest-sempa-test-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 httpx

      - name: Ingest (dry run)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          python scripts/ingest_sempa.py --urls-file scripts/urls.txt --out _tmp_out

      - name: Show output summary
        if: always()
        run: |
          echo "==== _tmp_out ===="
          ls -lah _tmp_out || true
          ls -lah _tmp_out/* || true
