name: Rebuild SEMPA embeddings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      PYTHONUNBUFFERED: "1"
      EMBED_MODEL: text-embedding-3-small
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Print run context
        run: |
          echo "run_id=$GITHUB_RUN_ID attempt=$GITHUB_RUN_ATTEMPT event=$GITHUB_EVENT_NAME ref=$GITHUB_REF_NAME"

      - name: Verify secrets
        run: |
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "::error::OPENAI_API_KEY is empty or missing"; exit 1
          fi

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt beautifulsoup4 httpx

      - name: Show URL preview (first 15)
        run: |
          test -f scripts/urls.txt || (echo "Missing scripts/urls.txt" && exit 1)
          head -n 15 scripts/urls.txt

      - name: 60s keepalive
        run: |
          for i in {1..6}; do echo "keepalive $i $(date -u +%H:%M:%S)"; sleep 10; done

      - name: Build embeddings (with signal trap)
        shell: bash
        timeout-minutes: 30
        run: |
          set -euo pipefail
          trap 'echo "::error::received cancel signal (INT/TE


