name: Ingest (test only, no commit)

on:
  workflow_dispatch:

concurrency:
  group: ingest-test
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt beautifulsoup4 httpx

      - name: Verify URL list
        run: |
          test -f scripts/urls.txt || (echo "Missing scripts/urls.txt" && exit 1)
          echo "First few URLs:" && sed -n '1,10p' scripts/urls.txt

      - name: Dry run ingest (no commit)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          python scripts/ingest_sempa.py --urls-file scripts/urls.txt --out /tmp/embeddings_test
          ls -la /tmp/embeddings_test
