name: Test SEMPA ingest (no commit)

on:
  workflow_dispatch: {}

concurrency:
  group: sempa-ingest-test-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  ingest-test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 httpx

      - name: Guard: missing OPENAI_API_KEY
        if: ${{ env.OPENAI_API_KEY == '' }}
        run: |
          echo "::error::OPENAI_API_KEY repository secret is not set."
          exit 1
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Ingest (test only)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          set -e
          echo "Start: $(date -Is)"
          python scripts/ingest_sempa.py ^
            --urls-file scripts/urls.txt ^
            --out clients/sempa/embeddings_v2
          echo "Done: $(date -Is)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sempa-embeddings-v2
          path: clients/sempa/embeddings_v2
