name: Test SEMPA ingest (no commit)

on:
  workflow_dispatch: {}

concurrency:
  group: sempa-ingest-test-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  ingest-test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 httpx

      - name: Ingest (test only, no commit)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          set -e
          python scripts/ingest_sempa.py --urls-file scripts/urls.txt --out clients/sempa/embeddings_v2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sempa-embeddings-v2
          path: clients/sempa/embeddings_v2
