name: Rebuild SEMPA embeddings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC

permissions:
  contents: write

# One live run at a time; new run cancels prior
concurrency:
  group: ingest-sempa-live
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4 httpx

      - name: Ingest (write to repo folder)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMBED_MODEL: text-embedding-3-small
        run: |
          python scripts/ingest_sempa.py --urls-file scripts/urls.txt --out clients/sempa/embeddings_v2

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add clients/sempa/embeddings_v2 || true
          git diff --cached --quiet && echo "No changes" || (git commit -m "chore: refresh embeddings_v2" && git push)
